image: node:10

stages:
  - build
  - test
  - deploy review
  - deploy staging
  - deploy production
  - production test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

variables:
  STAGING_DOMAIN: marc-staging.surge.sh
  PRODUCTION_DOMAIN: marc-production.surge.sh

build website:
  stage: build
  script:
  - npm install
  - npm install -g gatsby-cli
  - gatsby build
  artifacts:
    paths:
      - ./public/

test artifact:
  image: alpine
  stage: test
  script:
  - grep -q "Gatsby" ./public/index.html

# test website:
#   stage: test
#   script:
#   - npm install
#   - npm install -g gatsby-cli
#   - gatsby serve &
#   - sleep 15
#   - curl "http://localhost:9090/" | tac | tac | grep -q "Gatsby"

deploy review:
  only:
    - merge_request
  stage: deploy review
  script:
    - ls
    - pwd
    - npm install --global surge
    - surge --project ./public/ --domain $STAGING_DOMAIN
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://marc-$CI_COMMIT_REF_NAME.surge.sh

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  # only:
  #   - master
  script:
  - npm install --global surge
  - surge --project ./public/ --domain $STAGING_DOMAIN

deploy production:
  stage: deploy production
  environment:
    name: production
    url: http://$PRODUCTION_DOMAIN
  only:
    - master
  when: manual
  allow_failure: false
  script:
  - npm install --global surge
  - surge --project ./public/ --domain $PRODUCTION_DOMAIN





# production test:
#   image: alpine
#   stage: production test
#   only:
#     - master
#   script:
#   - apk add --no-cache curl
#   - curl -s "http://localhost:9090/" | tac | tac | grep -q "Hi people"
