image: node:10

stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
build website:
  stage: build
  script:
  - npm install
  - npm install -g gatsby-cli
  - gatsby build
  artifacts:
    paths:
      - ./public/

test artifact:
  image: alpine
  stage: test
  script:
  - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
  - npm install
  - npm install -g gatsby-cli
  - gatsby serve &
  - sleep 25
  - curl "http://localhost:9090/" | tac | tac | grep -q "Gatsby"

deploy to surge:
  stage: deploy
  script:
  - npm install --global surge
  - surge --project ./public/ --domain marc.surge.sh