stages:
  - build
  - test
build website:
  image: node:10
  script:
  - npm install
  - npm install -g gatsby-cli
  - gatsby build
  artifacts:
    paths:
      - ./public/

test artifact:
  image: alpine
  stage: test
  script:
  - grep "Gatsby" ./public/index.html 

test website:
  stage: test
  script:
  - gatsby serve
